name: build-jar

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: build new version
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assemble
    - name: 'Get Version Number'
      run: echo "version=$(./gradlew properties -q | grep 'version:' | awk '{print $2}')" >> $GITHUB_ENV
    - name: Print version
      run: echo $version
    - name: 'Publish JAR'
      uses: actions/upload-artifact@v2
      with:
        name: 'allure-piechart-telegram-${{env.version}}.jar'
        path: build/libs/*.jar
